// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJzCiKF1U-UgfKLK0vVcPrxcToKgMsWEo',
    appId: '1:1064569376034:web:9c56ecff49a12dfa78697b',
    messagingSenderId: '1064569376034',
    projectId: 'android-a986a',
    authDomain: 'android-a986a.firebaseapp.com',
    storageBucket: 'android-a986a.firebasestorage.app',
    measurementId: 'G-TKTN9STBT3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPs__B6fhMTyOjMiJNt2JuXgfSZhEtLYY',
    appId: '1:1064569376034:android:a4c12a372127cbba78697b',
    messagingSenderId: '1064569376034',
    projectId: 'android-a986a',
    storageBucket: 'android-a986a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkefHI5fm2jp_kNN5cmSelBVGNIFeUp90',
    appId: '1:1064569376034:ios:b8ac6589c33466d578697b',
    messagingSenderId: '1064569376034',
    projectId: 'android-a986a',
    storageBucket: 'android-a986a.firebasestorage.app',
    iosBundleId: 'com.example.flightsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkefHI5fm2jp_kNN5cmSelBVGNIFeUp90',
    appId: '1:1064569376034:ios:b8ac6589c33466d578697b',
    messagingSenderId: '1064569376034',
    projectId: 'android-a986a',
    storageBucket: 'android-a986a.firebasestorage.app',
    iosBundleId: 'com.example.flightsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJzCiKF1U-UgfKLK0vVcPrxcToKgMsWEo',
    appId: '1:1064569376034:web:25c7b84e3adfdbd878697b',
    messagingSenderId: '1064569376034',
    projectId: 'android-a986a',
    authDomain: 'android-a986a.firebaseapp.com',
    storageBucket: 'android-a986a.firebasestorage.app',
    measurementId: 'G-QPJF5S45C2',
  );

}